---
  - name: Install Updates(Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install docker
    shell:
      apt-get install docker.io -y
    when: ansible_distribution == "Ubuntu"

  - name: Install docker sdk
    shell:
      pip install docker-py
    when: ansible_distribution == "Ubuntu"

  - name: Add docker to group
    shell:
      usermod -aG docker $USER
    when: ansible_distribution == "Ubuntu"

  - name: Docker restarting / enabling
    service:
      name: docker
      state: restarted
      enabled: true
    when: ansible_distribution == "Ubuntu"

  - name: Create directory
    file:
      path: /root/demo-dockerfile.ubuntu
      state: directory
      owner: root
      group: root
      mode: 0755
    when: ansible_distribution == "Ubuntu"

  - name: Copy docker
    copy:
      src: ./dockerfile.ubuntu
      dest: /root/demo-dockerfile/dockerfile.ubuntu
      owner: root
      group: root
      mode: 0755
    when: ansible_distribution == "Ubuntu"

  - name: build container image
    command: >
      docker build
      --tag hoa11
      --build-arg listen_port=8080
      /root/demo-dockerfile
    when: ansible_distribution == "Ubuntu"

  - name: Access Containerized App
    shell: 
      docker run -it -d -p 8080:80 hoa11
    when: ansible_distribution == "Ubuntu"

